// <auto-generated />
using System;
using ConfeccionesEsperanzaEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConfeccionesEsperanzaEF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250924044510_VersionUno")]
    partial class VersionUno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Catalog.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("DescripcionCategoria")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("DescripcionCategoria")
                        .HasDatabaseName("IX_Categoria_Descripcion");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            DescripcionCategoria = "Camisas"
                        },
                        new
                        {
                            IdCategoria = 2,
                            DescripcionCategoria = "Pantalones"
                        },
                        new
                        {
                            IdCategoria = 3,
                            DescripcionCategoria = "Chaquetas"
                        },
                        new
                        {
                            IdCategoria = 4,
                            DescripcionCategoria = "Vestidos"
                        },
                        new
                        {
                            IdCategoria = 5,
                            DescripcionCategoria = "Sudaderas"
                        },
                        new
                        {
                            IdCategoria = 6,
                            DescripcionCategoria = "Shorts"
                        },
                        new
                        {
                            IdCategoria = 7,
                            DescripcionCategoria = "Faldas"
                        },
                        new
                        {
                            IdCategoria = 8,
                            DescripcionCategoria = "Buzos"
                        },
                        new
                        {
                            IdCategoria = 9,
                            DescripcionCategoria = "Blusas"
                        });
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Catalog.Color", b =>
                {
                    b.Property<int>("IdColor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColor"));

                    b.Property<string>("DescripcionColor")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdColor");

                    b.HasIndex("DescripcionColor")
                        .IsUnique()
                        .HasDatabaseName("IX_Color_Descripcion");

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            IdColor = 1,
                            DescripcionColor = "Rojo"
                        },
                        new
                        {
                            IdColor = 2,
                            DescripcionColor = "Azul"
                        },
                        new
                        {
                            IdColor = 3,
                            DescripcionColor = "Verde"
                        },
                        new
                        {
                            IdColor = 4,
                            DescripcionColor = "Amarillo"
                        },
                        new
                        {
                            IdColor = 5,
                            DescripcionColor = "Negro"
                        },
                        new
                        {
                            IdColor = 6,
                            DescripcionColor = "Blanco"
                        },
                        new
                        {
                            IdColor = 7,
                            DescripcionColor = "Gris"
                        },
                        new
                        {
                            IdColor = 8,
                            DescripcionColor = "Rosa"
                        },
                        new
                        {
                            IdColor = 9,
                            DescripcionColor = "Morado"
                        },
                        new
                        {
                            IdColor = 10,
                            DescripcionColor = "Naranja"
                        });
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Catalog.Familia", b =>
                {
                    b.Property<int>("IdFamilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFamilia"));

                    b.Property<string>("DescripcionFamilia")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdFamilia");

                    b.HasIndex("DescripcionFamilia")
                        .HasDatabaseName("IX_Familia_Descripcion");

                    b.ToTable("Familia");

                    b.HasData(
                        new
                        {
                            IdFamilia = 1,
                            DescripcionFamilia = "Ropa de invierno"
                        },
                        new
                        {
                            IdFamilia = 2,
                            DescripcionFamilia = "Ropa de verano"
                        },
                        new
                        {
                            IdFamilia = 3,
                            DescripcionFamilia = "Ropa deportiva"
                        },
                        new
                        {
                            IdFamilia = 4,
                            DescripcionFamilia = "Ropa casual"
                        },
                        new
                        {
                            IdFamilia = 5,
                            DescripcionFamilia = "Ropa formall"
                        },
                        new
                        {
                            IdFamilia = 6,
                            DescripcionFamilia = "Ropa de fiestal"
                        },
                        new
                        {
                            IdFamilia = 7,
                            DescripcionFamilia = "Ropa interior"
                        });
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Catalog.Linea", b =>
                {
                    b.Property<int>("IdLinea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLinea"));

                    b.Property<string>("DescripcionLinea")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdLinea");

                    b.HasIndex("DescripcionLinea")
                        .HasDatabaseName("IX_Linea_Descripcion");

                    b.ToTable("Linea");

                    b.HasData(
                        new
                        {
                            IdLinea = 1,
                            DescripcionLinea = "Hombre"
                        },
                        new
                        {
                            IdLinea = 2,
                            DescripcionLinea = "Mujer"
                        },
                        new
                        {
                            IdLinea = 3,
                            DescripcionLinea = "Niño"
                        },
                        new
                        {
                            IdLinea = 4,
                            DescripcionLinea = "Niña"
                        },
                        new
                        {
                            IdLinea = 5,
                            DescripcionLinea = "Unisex niños"
                        },
                        new
                        {
                            IdLinea = 6,
                            DescripcionLinea = "Unisex adultos"
                        });
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Catalog.Talla", b =>
                {
                    b.Property<int>("IdTalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTalla"));

                    b.Property<string>("DescripcionTalla")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdTalla");

                    b.HasIndex("DescripcionTalla")
                        .IsUnique()
                        .HasDatabaseName("IX_Talla_Descripcion");

                    b.ToTable("Talla");

                    b.HasData(
                        new
                        {
                            IdTalla = 1,
                            DescripcionTalla = "XS"
                        },
                        new
                        {
                            IdTalla = 2,
                            DescripcionTalla = "S"
                        },
                        new
                        {
                            IdTalla = 3,
                            DescripcionTalla = "M"
                        },
                        new
                        {
                            IdTalla = 4,
                            DescripcionTalla = "L"
                        },
                        new
                        {
                            IdTalla = 5,
                            DescripcionTalla = "XL"
                        },
                        new
                        {
                            IdTalla = 6,
                            DescripcionTalla = "XXL"
                        },
                        new
                        {
                            IdTalla = 7,
                            DescripcionTalla = "XXXL"
                        },
                        new
                        {
                            IdTalla = 8,
                            DescripcionTalla = "XXXXL"
                        },
                        new
                        {
                            IdTalla = 9,
                            DescripcionTalla = "8"
                        },
                        new
                        {
                            IdTalla = 10,
                            DescripcionTalla = "10"
                        },
                        new
                        {
                            IdTalla = 11,
                            DescripcionTalla = "12"
                        },
                        new
                        {
                            IdTalla = 12,
                            DescripcionTalla = "14"
                        });
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Customer.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("CodigoPostalCliente")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("DireccionCliente")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("NumeroDocCliente")
                        .HasColumnType("int");

                    b.Property<string>("TelefonoCliente")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("IdCliente");

                    b.HasIndex("EmailCliente")
                        .IsUnique()
                        .HasDatabaseName("IX_Cliente_Email");

                    b.HasIndex("NumeroDocCliente")
                        .IsUnique()
                        .HasDatabaseName("IX_Cliente_NumeroDoc");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Material.Material", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterial"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Color_IdColor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Proveedor")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("TipoMaterial_IdTipoMaterial")
                        .HasColumnType("int");

                    b.HasKey("IdMaterial");

                    b.HasIndex("Color_IdColor");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("IX_Material_Nombre");

                    b.HasIndex("TipoMaterial_IdTipoMaterial");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Material.TipoMaterial", b =>
                {
                    b.Property<int>("IdTipoMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoMaterial"));

                    b.Property<string>("DescripcionMaterial")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("UnidadMedida")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdTipoMaterial");

                    b.ToTable("TipoMaterial");

                    b.HasData(
                        new
                        {
                            IdTipoMaterial = 1,
                            DescripcionMaterial = "Tela de Algodón",
                            UnidadMedida = 1.0m
                        },
                        new
                        {
                            IdTipoMaterial = 2,
                            DescripcionMaterial = "Tela de Poliéster",
                            UnidadMedida = 1.0m
                        },
                        new
                        {
                            IdTipoMaterial = 3,
                            DescripcionMaterial = "Hilo",
                            UnidadMedida = 0.1m
                        },
                        new
                        {
                            IdTipoMaterial = 4,
                            DescripcionMaterial = "Botones",
                            UnidadMedida = 1.0m
                        },
                        new
                        {
                            IdTipoMaterial = 5,
                            DescripcionMaterial = "Cierre",
                            UnidadMedida = 1.0m
                        });
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Order.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Pedido_IdPedido")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Producto_IdProducto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Pedido_IdPedido");

                    b.HasIndex("Producto_IdProducto");

                    b.ToTable("DetallePedido");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Order.Pedidos", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<int>("Cliente_IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPedido");

                    b.HasIndex("Cliente_IdCliente");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_Pedidos_Estado");

                    b.HasIndex("FechaRegistro")
                        .HasDatabaseName("IX_Pedidos_FechaRegistro");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Product.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<int>("Categoria_IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("Color_IdColor")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Familia_IdFamilia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Linea_IdLinea")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("Talla_IdTalla")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.HasIndex("Categoria_IdCategoria");

                    b.HasIndex("Color_IdColor");

                    b.HasIndex("Familia_IdFamilia");

                    b.HasIndex("Linea_IdLinea");

                    b.HasIndex("NombreProducto")
                        .HasDatabaseName("IX_Producto_Nombre");

                    b.HasIndex("Talla_IdTalla");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Product.ProductoMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CantidadRequerida")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Material_IdMaterial")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Producto_IdProducto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Material_IdMaterial");

                    b.HasIndex("Producto_IdProducto", "Material_IdMaterial")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductoMaterial_Unique");

                    b.ToTable("ProductoMaterial");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Production.Tarea", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarea"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreTarea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTarea");

                    b.HasIndex("NombreTarea")
                        .HasDatabaseName("IX_Tarea_Nombre");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Production.UsuarioProductoTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Producto_IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("Tarea_IdTarea")
                        .HasColumnType("int");

                    b.Property<string>("Usuario_IdUsuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_UsuarioProductoTarea_Estado");

                    b.HasIndex("Producto_IdProducto");

                    b.HasIndex("Tarea_IdTarea");

                    b.HasIndex("Usuario_IdUsuario", "Producto_IdProducto", "Tarea_IdTarea")
                        .HasDatabaseName("IX_UsuarioProductoTarea_Unique");

                    b.ToTable("UsuarioProductoTarea");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Material.Material", b =>
                {
                    b.HasOne("ConfeccionesEsperanzaEF.Models.Catalog.Color", "Color")
                        .WithMany("Materiales")
                        .HasForeignKey("Color_IdColor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfeccionesEsperanzaEF.Models.Material.TipoMaterial", "TipoMaterial")
                        .WithMany("Materiales")
                        .HasForeignKey("TipoMaterial_IdTipoMaterial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("TipoMaterial");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Order.DetallePedido", b =>
                {
                    b.HasOne("ConfeccionesEsperanzaEF.Models.Order.Pedidos", "Pedido")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("Pedido_IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfeccionesEsperanzaEF.Models.Product.Producto", "Producto")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("Producto_IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Order.Pedidos", b =>
                {
                    b.HasOne("ConfeccionesEsperanzaEF.Models.Customer.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("Cliente_IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Product.Producto", b =>
                {
                    b.HasOne("ConfeccionesEsperanzaEF.Models.Catalog.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Categoria_IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfeccionesEsperanzaEF.Models.Catalog.Color", "Color")
                        .WithMany("Productos")
                        .HasForeignKey("Color_IdColor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfeccionesEsperanzaEF.Models.Catalog.Familia", "Familia")
                        .WithMany("Productos")
                        .HasForeignKey("Familia_IdFamilia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfeccionesEsperanzaEF.Models.Catalog.Linea", "Linea")
                        .WithMany("Productos")
                        .HasForeignKey("Linea_IdLinea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfeccionesEsperanzaEF.Models.Catalog.Talla", "Talla")
                        .WithMany("Productos")
                        .HasForeignKey("Talla_IdTalla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Color");

                    b.Navigation("Familia");

                    b.Navigation("Linea");

                    b.Navigation("Talla");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Product.ProductoMaterial", b =>
                {
                    b.HasOne("ConfeccionesEsperanzaEF.Models.Material.Material", "Material")
                        .WithMany("ProductoMateriales")
                        .HasForeignKey("Material_IdMaterial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfeccionesEsperanzaEF.Models.Product.Producto", "Producto")
                        .WithMany("ProductoMateriales")
                        .HasForeignKey("Producto_IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Production.UsuarioProductoTarea", b =>
                {
                    b.HasOne("ConfeccionesEsperanzaEF.Models.Product.Producto", "Producto")
                        .WithMany("UsuarioProductoTareas")
                        .HasForeignKey("Producto_IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfeccionesEsperanzaEF.Models.Production.Tarea", "Tarea")
                        .WithMany("UsuarioProductoTareas")
                        .HasForeignKey("Tarea_IdTarea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuario_IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Catalog.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Catalog.Color", b =>
                {
                    b.Navigation("Materiales");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Catalog.Familia", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Catalog.Linea", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Catalog.Talla", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Customer.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Material.Material", b =>
                {
                    b.Navigation("ProductoMateriales");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Material.TipoMaterial", b =>
                {
                    b.Navigation("Materiales");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Order.Pedidos", b =>
                {
                    b.Navigation("DetallesPedido");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Product.Producto", b =>
                {
                    b.Navigation("DetallesPedido");

                    b.Navigation("ProductoMateriales");

                    b.Navigation("UsuarioProductoTareas");
                });

            modelBuilder.Entity("ConfeccionesEsperanzaEF.Models.Production.Tarea", b =>
                {
                    b.Navigation("UsuarioProductoTareas");
                });
#pragma warning restore 612, 618
        }
    }
}
